# Generated by Django 2.1.5 on 2020-03-09 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDeCuenta', models.CharField(default='', max_length=20)),
                ('Telefono', models.CharField(default='', max_length=20)),
                ('TelefonoAlternativo', models.CharField(default='', max_length=20)),
                ('TipoSangre', models.CharField(default='', max_length=4)),
                ('Alergias', models.CharField(default='', max_length=30)),
                ('DatoPersonalFk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=20)),
                ('Licencia', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('Dirrecion', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreRuta', models.CharField(default='', max_length=20)),
                ('Horario', models.CharField(default='', max_length=30)),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=10)),
                ('Tipo', models.CharField(max_length=10)),
                ('Matricula', models.CharField(max_length=10)),
                ('OperadorFK', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.Operador')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='TransporteFK',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.Transporte'),
        ),
    ]
