# Generated by Django 2.1.5 on 2020-03-10 01:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potrotransporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('s', 'Semestral'), ('e', 'Semanal'), ('m', 'Mensual')], default='e', max_length=1)),
                ('fechaCreacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('monto', models.FloatField(default=500)),
                ('estatus', models.CharField(choices=[('P', 'Pagado'), ('C', 'Cancelado'), ('E', 'Pendiente'), ('N', 'Nuevo')], default='N', max_length=1)),
                ('UsuarioFK', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
