# Generated by Django 2.1.5 on 2020-03-10 01:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potrotransporte', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAprobacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('fechaExpiracion', models.DateField(default=datetime.datetime.today, verbose_name='Fecha')),
                ('UserAdministrativo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pagoFk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.Pago')),
            ],
        ),
    ]
