# Generated by Django 2.1.5 on 2020-03-10 02:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potrotransporte', '0003_aprobacionpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ida', models.BooleanField(default=True)),
                ('vuelta', models.BooleanField(default=True)),
                ('fechaDeReserva', models.DateTimeField(default=datetime.date(2020, 3, 11), verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('RutaFk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.Ruta')),
                ('UsuarioFK', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ReservaFK',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.Reserva'),
        ),
    ]
