# Generated by Django 2.1.5 on 2020-04-15 02:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potrotransporte', '0004_auto_20200310_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='detallePagoMembresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoPago', models.CharField(choices=[('P', 'Pagado'), ('C', 'Cancelado'), ('E', 'Pendiente')], default='E', max_length=1)),
                ('Activo', models.BooleanField()),
                ('FechaAprobacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaCreacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('FechaTerminacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMembresias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('costo', models.IntegerField()),
                ('duracion', models.CharField(choices=[('S', 'Semanal'), ('M', 'Mensual'), ('C', 'Semestral')], default='C', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='aprobacionpago',
            name='UserAdministrativo',
        ),
        migrations.RemoveField(
            model_name='aprobacionpago',
            name='pagoFk',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='UsuarioFK',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fechaDeReserva',
            field=models.DateTimeField(default=datetime.date(2020, 4, 16), verbose_name='Fecha'),
        ),
        migrations.DeleteModel(
            name='AprobacionPago',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.AddField(
            model_name='membresia',
            name='MembresiaFk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.TipoMembresias'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='UsuarioFk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepagomembresia',
            name='MembresiaFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potrotransporte.Membresia'),
        ),
        migrations.AddField(
            model_name='detallepagomembresia',
            name='administrativoFK',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
