# Generated by Django 2.1.5 on 2020-04-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrotransporte', '0005_auto_20200415_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepagomembresia',
            name='EstadoPago',
        ),
        migrations.AddField(
            model_name='membresia',
            name='EstadoPago',
            field=models.CharField(choices=[('P', 'Pagado'), ('C', 'Cancelado'), ('E', 'Pendiente')], default='E', max_length=1),
        ),
    ]
