# Generated by Django 2.1.5 on 2020-04-16 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # **<<< HERE**

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potrotransporte', '0007_auto_20200415_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='RutaReserva',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='costo',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='turno',
            field=models.CharField(choices=[('V', 'Vespertino'), ('M', 'Matutino')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='tipomembresias',
            name='costoPorDuracion',
            field=models.IntegerField(default=0),
        ),
    ]
