# Generated by Django 2.1.5 on 2020-04-16 01:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('potrotransporte', '0008_auto_20200415_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('cuerpo', models.CharField(max_length=30)),
                ('fechaCreacion', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='fechaDeReserva',
            new_name='fechaDeIda',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='turno',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fechaVuelta',
            field=models.DateTimeField(default=datetime.date(2020, 4, 16), verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='rutareserva',
            name='estadoReserva',
            field=models.CharField(choices=[('P', 'Reservado'), ('C', 'Cancelado')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='rutareserva',
            name='turno',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='ida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='vuelta',
            field=models.BooleanField(default=False),
        ),
    ]
