# Generated by Django 2.1.5 on 2020-04-21 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrotransporte', '0009_auto_20200415_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='FechaInicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fechaDeIda',
            field=models.DateTimeField(default=datetime.date(2020, 4, 22), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fechaVuelta',
            field=models.DateTimeField(default=datetime.date(2020, 4, 22), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detallepagomembresia',
            name='FechaAprobacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Aprobacion'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='EstadoPago',
            field=models.CharField(choices=[('P', 'Pagado'), ('C', 'Cancelado'), ('E', 'Pendiente'), ('T', 'Cancelado Tiempo'), ('W', 'Expiro Membresia')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='FechaCreacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha creacion'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='FechaTerminacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Terminacion'),
        ),
    ]
